version: '3.8'

services:
  nexus-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://80.89.238.37:8000/api
    ports:
      - "80:80"
    restart: always
    container_name: nexus-pay-frontend
